
@startuml

' skinparam linetype ortho
' scale 0.6

component PC as pPc {

	rectangle "Your Tools" as pTools {

		frame "Programmer" as pProg
		frame "Debugger (GDB)" as pDbg

		frame "Process Tree" as pTree
		frame "Log" as pLog
		frame "Command" as pCmd
		' frame "Custom\nChannels" as pCustom
	}

	frame "CodeOrb" as pGw
	frame "STMicroelectronics\nSoftware" as pStSw

	frame "ST-Link Driver" as pDrv

	pProg --> pStSw
	pDbg <--> pStSw

	pTree <-[thickness=2]- pGw
	pLog <-[thickness=2]- pGw
	pCmd <-[thickness=2]-> pGw : "TCP/IP"
	' pCustom <-[thickness=2]-> pGw

	pStSw <--> pDrv
	pGw <--> pDrv : "COM1 or\n/dev/ttyACM0"

	pStSw -r[hidden]- pGw
}

component "NUCLEO" as pNuc {

	component "STM32" {

		component "Programming and\nDebug Hardware Module" as pHwDbg

		frame "<<SystemDebugging()>>" as pSysDbg #lightblue {
			' frame "<<SingleWireTransfering()>>" as pSwt #lightblue
		}

		frame "<<AppProcessing()>>" as pApp #lightblue

		pHwDbg <--> pApp
		pSysDbg <--> pApp
	}

	component "ST-Link" as pStLink

	pStLink <--> pHwDbg : SWD
	pStLink <--> pSysDbg : USART2
}

pDrv <--> pStLink : USB

footer **Processing()** - Debugging STM32 Targets\n(C) DSP-Crowd Electronics GmbH

@enduml

