
@startuml

' skinparam linetype ortho

component PC as pc {
  frame "Python Gateway" as gw

  frame "Log" as log
  frame "Command" as cmd
  frame "Process Tree" as tree

  frame "Client 1" as clt1
  frame "Client 2" as clt2

  frame "Programmer and\nDebugger Software" as dbgPc
  frame "Application Source\nVersion = ???" as src
}

component "Converter from\nUART to USB" as cnvt2

component "Target STM32 with UART" as trg {
  frame "SystemDebugging()" as dbg
  frame "SingleWireTransfering()" as swt
  component "Programming and\nDebug Hardware Module" as segInt
  frame "AppProcessing()" as app

  component "ST-Link" as seg
}

dbg <-> app
dbg <--> swt
app <--> segInt

gw -[hidden]r- dbgPc

swt -[hidden]r- segInt
swt <--> cnvt2 : UART

cnvt2 <--> gw : USB

segInt <-> seg

seg <--> dbgPc : USB
dbgPc <-- src

gw --> log
gw <--> cmd
tree <- gw

tree --> clt1
log --> clt1
log --> clt2
cmd <--> clt1
cmd <--> clt2

footer **Processing()** STM32 Targets with UART as communication channel\n(C) DSP-Crowd Electronics GmbH

@enduml

